// Package claude renders canonical agents/skills/instructions into Claude Code's layout.
//
//	<outRoot>/.claude/CLAUDE.md            (claude-prefix.md + global.md)
//	<outRoot>/.claude/agents/<name>.md     (only agents that target=claude)
//	<outRoot>/.claude/skills/<name>/       (verbatim copy)
//
// Claude's agent frontmatter is: name, description, tools, model.
// Tool names are capitalized (Read, Bash, Grep, Glob). Model is an alias
// (opus, sonnet, haiku) or omitted (Claude Code uses session default).
// Pi-only fields are dropped.
package claude

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jsmestad/syncai/internal/load"
	"github.com/jsmestad/syncai/internal/profiles"
	"github.com/jsmestad/syncai/internal/renderers"
	"github.com/jsmestad/syncai/internal/schema"
)

const generatedHeader = "<!-- Generated by syncai from ai-source. Do not edit directly. Run `make ai-sync`. -->\n\n"

// toolMap translates the source tool vocabulary (Pi-style lowercase) to the
// names Claude Code recognizes. Claude has fewer, broader tools — `find` and
// `ls` both collapse to `Glob`, and `read`/`bash`/`grep` capitalise.
var toolMap = map[string]string{
	"read":  "Read",
	"bash":  "Bash",
	"grep":  "Grep",
	"glob":  "Glob",
	"find":  "Glob",
	"ls":    "Glob",
	"edit":  "Edit",
	"write": "Write",
}

type Renderer struct{}

func New() Renderer { return Renderer{} }

func (Renderer) Name() string { return string(schema.TargetClaude) }

func (Renderer) Render(in renderers.Inputs, outRoot string) ([]string, error) {
	if in.ProjectMode {
		// Claude Code is configured globally; project-local renders skip it.
		return nil, nil
	}
	root := filepath.Join(outRoot, ".claude")
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, err
	}
	var written []string

	w, err := writeAgents(root, in)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	w, err = writeSkills(root, in.SkillDirs)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	if in.InstructionsGlobal != "" {
		path := filepath.Join(root, "CLAUDE.md")
		body := assembleInstructions(in.InstructionPrefixes[string(schema.TargetClaude)], in.InstructionsGlobal)
		if err := load.WriteFileReplacing(path, []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, path)
	}
	return written, nil
}

func writeAgents(root string, in renderers.Inputs) ([]string, error) {
	dir := filepath.Join(root, "agents")
	var written []string
	for _, a := range in.Agents {
		if !a.HasTarget(schema.TargetClaude) {
			continue
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
		body, err := renderAgent(a, in.Profiles)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(dir, a.Name+".md")
		if err := load.WriteFileReplacing(path, body, 0o644); err != nil {
			return nil, fmt.Errorf("writing %s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}

func writeSkills(root string, srcDirs []string) ([]string, error) {
	if len(srcDirs) == 0 {
		return nil, nil
	}
	dst := filepath.Join(root, "skills")
	var written []string
	for _, src := range srcDirs {
		target := filepath.Join(dst, filepath.Base(src))
		if err := load.CopyDir(src, target); err != nil {
			return nil, fmt.Errorf("copying skill %s: %w", filepath.Base(src), err)
		}
		written = append(written, target)
	}
	return written, nil
}

func renderAgent(a *schema.Agent, p *profiles.File) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("---\n")
	for _, kv := range a.Fields {
		switch kv.Key {
		case "targets", "scope":
			continue
		case "tools":
			fmt.Fprintf(&b, "tools: %s\n", translateTools(kv.Value))
			continue
		case "modelRole":
			model, err := resolveModel(p, kv.Value)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", a.Path, err)
			}
			if model != "" {
				fmt.Fprintf(&b, "model: %s\n", model)
			}
			continue
		case "model", "fallbackModels":
			continue
		}
		if _, ok := schema.PiOnlyFields[kv.Key]; ok {
			continue
		}
		fmt.Fprintf(&b, "%s: %s\n", kv.Key, kv.Value)
	}
	b.WriteString("---\n")
	b.WriteString(a.Body)
	return b.Bytes(), nil
}

// translateTools maps the comma-separated source tool list to Claude's
// vocabulary. Unknown names pass through with first-letter capitalisation
// so users can introduce new tools without updating this map.
func translateTools(csv string) string {
	in := schema.SplitCSV(csv)
	seen := map[string]bool{}
	var out []string
	for _, name := range in {
		mapped, ok := toolMap[strings.ToLower(name)]
		if !ok {
			mapped = capitalise(name)
		}
		if seen[mapped] {
			continue
		}
		seen[mapped] = true
		out = append(out, mapped)
	}
	return strings.Join(out, ", ")
}

func capitalise(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// resolveModel looks up the role for the claude target. Claude is a fixed
// target (single provider), so model-profiles.json/fixed.claude is consulted
// regardless of activeProfile. Returns ("", nil) when no claude target is
// declared — Claude Code falls back to the session default.
func resolveModel(p *profiles.File, role string) (string, error) {
	if p == nil || !p.HasTarget(string(schema.TargetClaude)) {
		return "", nil
	}
	return p.Resolve(string(schema.TargetClaude), role)
}

func assembleInstructions(prefix, global string) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	if prefix != "" {
		b.WriteString(strings.TrimRight(prefix, "\n"))
		b.WriteString("\n\n---\n\n")
	}
	b.WriteString(strings.TrimRight(global, "\n"))
	b.WriteString("\n")
	return b.String()
}
