// Package opencode renders canonical agents into OpenCode's layout.
//
// Per https://opencode.ai/docs/agents, OpenCode stores agents as markdown at
// ~/.config/opencode/agents/<name>.md (filename = agent identifier; no `name`
// field). Frontmatter: description, mode, model, temperature, permission,
// prompt, steps. There is no `tools` field — tool access is configured via
// the `permission` map (edit/bash/etc deny|ask|allow).
//
// Output layout:
//
//	<outRoot>/.config/opencode/AGENTS.md       (instructions/global.md)
//	<outRoot>/.config/opencode/agents/<name>.md (only agents that target=opencode)
package opencode

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/jsmestad/syncai/internal/load"
	"github.com/jsmestad/syncai/internal/profiles"
	"github.com/jsmestad/syncai/internal/renderers"
	"github.com/jsmestad/syncai/internal/schema"
)

const generatedHeader = "<!-- Generated by syncai from ai-source. Do not edit directly. Run `make ai-sync`. -->\n\n"

// permissionFor maps source tool names to the OpenCode permission key they
// govern. Tools not in the source list become `deny` in the output.
var permissionFor = map[string]string{
	"bash":  "bash",
	"edit":  "edit",
	"write": "edit",
	"read":  "read",
	"grep":  "read",
	"find":  "read",
	"glob":  "read",
	"ls":    "read",
}

// permissionKeys lists every OpenCode permission slot we emit. Anything not
// granted by the source tool list defaults to "deny".
var permissionKeys = []string{"edit", "bash", "read"}

type Renderer struct{}

func New() Renderer { return Renderer{} }

func (Renderer) Name() string { return string(schema.TargetOpenCode) }

func (Renderer) Render(in renderers.Inputs, outRoot string) ([]string, error) {
	if in.ProjectMode {
		return nil, nil
	}
	root := filepath.Join(outRoot, ".config", "opencode")
	if err := load.MkdirAll(outRoot, root, 0o755); err != nil {
		return nil, err
	}
	var written []string

	w, err := writeAgents(outRoot, root, in)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	if in.InstructionsGlobal != "" {
		path := filepath.Join(root, "AGENTS.md")
		body := generatedHeader + strings.TrimRight(in.InstructionsGlobal, "\n") + "\n"
		if err := load.WriteFileReplacing(outRoot, path, []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, path)
	}
	return written, nil
}

func writeAgents(outRoot, root string, in renderers.Inputs) ([]string, error) {
	dir := filepath.Join(root, "agents")
	var written []string
	for _, a := range in.Agents {
		if !a.HasTarget(schema.TargetOpenCode) {
			continue
		}
		if err := load.MkdirAll(outRoot, dir, 0o755); err != nil {
			return nil, err
		}
		body, err := renderAgent(a, in.Profiles)
		if err != nil {
			return nil, err
		}
		// Filename is the agent identifier in OpenCode.
		path := filepath.Join(dir, a.Name+".md")
		if err := load.WriteFileReplacing(dir, path, body, 0o644); err != nil {
			return nil, fmt.Errorf("writing %s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}

func renderAgent(a *schema.Agent, p *profiles.File) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("---\n")
	fmt.Fprintf(&b, "description: %s\n", a.Description)
	b.WriteString("mode: subagent\n")

	if role := a.Lookup("modelRole"); role != "" {
		model, err := resolveModel(p, role)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", a.Path, err)
		}
		if model != "" {
			fmt.Fprintf(&b, "model: %s\n", model)
		}
	}

	writePermission(&b, a.Lookup("tools"))

	b.WriteString("---\n")
	b.WriteString(a.Body)
	return b.Bytes(), nil
}

// writePermission emits the YAML permission map. Keys not granted by the
// source tool list default to "deny".
func writePermission(b *bytes.Buffer, toolsCSV string) {
	granted := map[string]bool{}
	for _, t := range schema.SplitCSV(toolsCSV) {
		if perm, ok := permissionFor[strings.ToLower(t)]; ok {
			granted[perm] = true
		}
	}
	b.WriteString("permission:\n")
	for _, key := range permissionKeys {
		val := "deny"
		if granted[key] {
			val = "allow"
		}
		fmt.Fprintf(b, "  %s: %s\n", key, val)
	}
}

// resolveModel looks up the role for the opencode target. OpenCode is a
// toggleable target — its mapping lives under profiles.<active>.opencode and
// switches when activeProfile changes.
func resolveModel(p *profiles.File, role string) (string, error) {
	if p == nil || !p.HasTarget(string(schema.TargetOpenCode)) {
		return "", nil
	}
	return p.Resolve(string(schema.TargetOpenCode), role)
}
