package cli

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jsmestad/syncai/internal/manifest"
	"github.com/jsmestad/syncai/internal/renderers"
	"github.com/jsmestad/syncai/internal/renderers/codex"
)

type missingOutputRenderer struct {
	path string
}

type removingRenderer struct {
	relativePath string
}

func (renderer removingRenderer) Name() string {
	return "removing"
}

func (renderer removingRenderer) Render(_ renderers.Inputs, outRoot string) ([]string, error) {
	return nil, os.Remove(filepath.Join(outRoot, renderer.relativePath))
}

func (renderer missingOutputRenderer) Name() string {
	return "missing"
}

func (renderer missingOutputRenderer) Render(renderers.Inputs, string) ([]string, error) {
	return []string{renderer.path}, nil
}

func TestRenderDoesNotReplaceManifestWhenOutputClassificationFails(t *testing.T) {
	stateRoot := t.TempDir()
	t.Setenv("XDG_STATE_HOME", stateRoot)
	manifestPath, err := manifest.DefaultPath()
	if err != nil {
		t.Fatal(err)
	}
	old := &manifest.Manifest{Scope: "work", Files: []manifest.FileEntry{{Path: "existing", Hash: "hash"}}}
	if err := manifest.Save(manifestPath, old); err != nil {
		t.Fatal(err)
	}
	before, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}

	app := New(Streams{In: strings.NewReader(""), Out: &bytes.Buffer{}, Err: &bytes.Buffer{}})
	app.renderers = []renderers.Renderer{missingOutputRenderer{path: filepath.Join(t.TempDir(), "missing")}}
	err = app.Execute(context.Background(), []string{"render", "--source", completeExampleSource(t), "--profile", "balanced"})
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("expected missing output error, got %v", err)
	}
	after, readErr := os.ReadFile(manifestPath)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if !bytes.Equal(after, before) {
		t.Fatalf("manifest changed after classification failure:\n%s", after)
	}
}

func TestUnreconciledDriftAcceptsCurrentCodexInstructions(t *testing.T) {
	out := t.TempDir()
	path := filepath.Join(out, ".codex", "AGENTS.md")
	rtkInclude := "@/Users/example/.codex/RTK.md"
	installed := "<!-- Generated by syncai from ai-source. Do not edit directly. Run `make ai-sync`. -->\n\ncanonical instructions\n\n" + rtkInclude + "\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(installed), 0o644); err != nil {
		t.Fatal(err)
	}

	unreconciled, err := unreconciledDrift(context.Background(), renderers.Inputs{InstructionsGlobal: "canonical instructions"}, out, []string{path}, []renderers.Renderer{codex.New()})
	if err != nil {
		t.Fatal(err)
	}
	if len(unreconciled) != 0 {
		t.Fatalf("expected equivalent instructions to reconcile, got %v", unreconciled)
	}
}

func TestUnreconciledDriftReturnsShadowReadError(t *testing.T) {
	out := t.TempDir()
	path := filepath.Join(out, ".codex", "AGENTS.md")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("installed"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err := unreconciledDrift(context.Background(), renderers.Inputs{}, out, []string{path}, []renderers.Renderer{removingRenderer{relativePath: filepath.Join(".codex", "AGENTS.md")}})
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("expected missing shadow output error, got %v", err)
	}
}

func TestRunCheckModePreservesCodexRTKInclude(t *testing.T) {
	source := completeExampleSource(t)
	out := t.TempDir()
	var stdout bytes.Buffer
	app := New(Streams{In: strings.NewReader(""), Out: &stdout, Err: &bytes.Buffer{}})
	if err := app.Execute(context.Background(), []string{"render", "--source", source, "--out", out, "--profile", "balanced"}); err != nil {
		t.Fatalf("rendering complete example: %v", err)
	}

	path := filepath.Join(out, ".codex", "AGENTS.md")
	installed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(installed, []byte("\n@/Users/example/.codex/RTK.md\n")...), 0o644); err != nil {
		t.Fatal(err)
	}

	stdout.Reset()
	if err := app.Execute(context.Background(), []string{"render", "--source", source, "--out", out, "--profile", "balanced", "--check"}); err != nil {
		t.Fatalf("expected RTK-preserving render check to pass: %v", err)
	}
}

func TestUnreconciledDriftRejectsLocalCodexInstructions(t *testing.T) {
	out := t.TempDir()
	path := filepath.Join(out, ".codex", "AGENTS.md")
	installed := "<!-- Generated by syncai from ai-source. Do not edit directly. Run `make ai-sync`. -->\n\ncanonical instructions\n\nlocal instruction\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(installed), 0o644); err != nil {
		t.Fatal(err)
	}

	unreconciled, err := unreconciledDrift(context.Background(), renderers.Inputs{InstructionsGlobal: "canonical instructions"}, out, []string{path}, []renderers.Renderer{codex.New()})
	if err != nil {
		t.Fatal(err)
	}
	if len(unreconciled) != 1 || unreconciled[0] != path {
		t.Fatalf("expected local instructions to remain drifted, got %v", unreconciled)
	}
}
