// Package pi renders canonical agents/skills/instructions/extensions into
// Pi's layout.
//
// Global mode (default):
//
//	<outRoot>/.pi/agent/agents/<name>.md
//	<outRoot>/.pi/agent/skills/<name>/         (verbatim copy)
//	<outRoot>/.pi/agent/extensions/<name>.ts   (verbatim copy, Pi-only)
//	<outRoot>/.pi/agent/extensions/<name>/     (verbatim copy directory)
//	<outRoot>/.pi/agent/AGENTS.md              (instructions/global.md)
//	<outRoot>/.pi/agent/model-profiles.json    (verbatim copy)
//
// Project mode (`syncai render --project <path>`):
//
//	<outRoot>/.pi/agents/<name>.md
//	<outRoot>/.pi/skills/<name>/
//	<outRoot>/AGENTS.md
//	<outRoot>/.pi/model-profiles.generated.json
//
// Pi renders source agents into @tintinweb/pi-subagents' frontmatter schema.
// modelRole resolves against the active profile's "pi" target, then splits its
// optional thinking suffix into the extension's separate model and thinking fields.
package pi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/jsmestad/syncai/internal/load"
	"github.com/jsmestad/syncai/internal/profiles"
	"github.com/jsmestad/syncai/internal/renderers"
	"github.com/jsmestad/syncai/internal/schema"
)

const generatedHeader = "<!-- Generated by syncai from ai-source. Do not edit directly. Run `make ai-sync`. -->\n\n"

type Renderer struct{}

func New() Renderer { return Renderer{} }

func (Renderer) Name() string { return string(schema.TargetPi) }

func (Renderer) Render(in renderers.Inputs, outRoot string) ([]string, error) {
	layout := globalLayout(outRoot)
	if in.ProjectMode {
		layout = projectLayout(outRoot)
	}

	var written []string
	w, err := writeAgents(outRoot, layout.agentsDir, in)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	w, err = writeSkills(outRoot, layout.skillsDir, in.SkillDirs)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	w, err = writeExtensions(outRoot, layout.extensionsDir, in.Extensions)
	if err != nil {
		return nil, err
	}
	written = append(written, w...)

	if in.InstructionsGlobal != "" {
		body := generatedHeader + strings.TrimRight(in.InstructionsGlobal, "\n")
		if prefix := strings.TrimSpace(in.InstructionPrefixes[string(schema.TargetPi)]); prefix != "" {
			body += "\n\n---\n\n" + prefix
		}
		body += "\n"
		if err := load.WriteFileReplacing(outRoot, layout.instructionsPath, []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, layout.instructionsPath)
	}

	if in.Profiles != nil {
		raw, err := json.MarshalIndent(in.Profiles, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("encoding resolved model profiles: %w", err)
		}
		if err := load.WriteFileReplacing(outRoot, layout.profilesPath, append(raw, '\n'), 0o644); err != nil {
			return nil, err
		}
		written = append(written, layout.profilesPath)
	}
	return written, nil
}

type piLayout struct {
	agentsDir        string
	skillsDir        string
	extensionsDir    string
	instructionsPath string
	profilesPath     string
}

func globalLayout(outRoot string) piLayout {
	root := filepath.Join(outRoot, ".pi", "agent")
	return piLayout{
		agentsDir:        filepath.Join(root, "agents"),
		skillsDir:        filepath.Join(root, "skills"),
		extensionsDir:    filepath.Join(root, "extensions"),
		instructionsPath: filepath.Join(root, "AGENTS.md"),
		profilesPath:     filepath.Join(root, "model-profiles.json"),
	}
}

func projectLayout(outRoot string) piLayout {
	piDir := filepath.Join(outRoot, ".pi")
	return piLayout{
		agentsDir:        filepath.Join(piDir, "agents"),
		skillsDir:        filepath.Join(piDir, "skills"),
		extensionsDir:    filepath.Join(piDir, "extensions"),
		instructionsPath: filepath.Join(outRoot, "AGENTS.md"),
		profilesPath:     filepath.Join(piDir, "model-profiles.generated.json"),
	}
}

func writeAgents(outRoot, dir string, in renderers.Inputs) ([]string, error) {
	if err := load.MkdirAll(outRoot, dir, 0o755); err != nil {
		return nil, err
	}
	if err := removeLegacyChainFiles(dir); err != nil {
		return nil, err
	}
	var written []string
	for _, a := range in.Agents {
		if !a.HasTarget(schema.TargetPi) || strings.HasSuffix(a.Path, ".chain.md") {
			continue
		}
		body, err := renderAgent(a, in.Profiles)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(dir, a.Name+".md")
		if err := load.WriteFileReplacing(dir, path, body, 0o644); err != nil {
			return nil, fmt.Errorf("writing %s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}

func removeLegacyChainFiles(dir string) error {
	matches, err := filepath.Glob(filepath.Join(dir, "*.chain.md"))
	if err != nil {
		return fmt.Errorf("finding legacy chain files: %w", err)
	}
	for _, path := range matches {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("removing legacy chain file %s: %w", path, err)
		}
	}
	return nil
}

func writeSkills(outRoot, dst string, srcDirs []string) ([]string, error) {
	if len(srcDirs) == 0 {
		return nil, nil
	}
	var written []string
	for _, src := range srcDirs {
		name := filepath.Base(src)
		target := filepath.Join(dst, name)
		if err := load.CopyDir(outRoot, src, target); err != nil {
			return nil, fmt.Errorf("copying skill %s: %w", name, err)
		}
		written = append(written, target)
	}
	return written, nil
}

// writeExtensions copies Pi-only TS extensions into <dst>. Single-file
// extensions land at <dst>/<name>.ts; directory extensions at <dst>/<name>/.
// The TOML sidecars from the source tree are intentionally not copied —
// they're build-time metadata, not runtime config Pi cares about.
func writeExtensions(outRoot, dst string, exts []*schema.Extension) ([]string, error) {
	if len(exts) == 0 {
		return nil, nil
	}
	if err := load.MkdirAll(outRoot, dst, 0o755); err != nil {
		return nil, err
	}
	var written []string
	for _, e := range exts {
		target := filepath.Join(dst, e.InstallName())
		if e.IsDirectory {
			if err := load.CopyDir(outRoot, e.SourcePath, target); err != nil {
				return nil, fmt.Errorf("copying extension %s: %w", e.Name, err)
			}
			// CopyDir is a recursive copy and will pull in the sidecar.
			// Strip it from the install tree — Pi doesn't load it and a
			// stray TOML in node_modules-adjacent directories is confusing.
			sidecar := filepath.Join(target, "extension.toml")
			if err := os.Remove(sidecar); err != nil && !os.IsNotExist(err) {
				return nil, fmt.Errorf("removing sidecar from install tree: %w", err)
			}
			written = append(written, target)
			continue
		}
		if err := load.CopyFileReplacing(outRoot, e.SourcePath, target); err != nil {
			return nil, fmt.Errorf("copying extension %s: %w", e.Name, err)
		}
		written = append(written, target)
	}
	return written, nil
}

func renderAgent(a *schema.Agent, p *profiles.File) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("---\n")
	for _, kv := range a.Fields {
		switch kv.Key {
		case "description", "display_name":
			fmt.Fprintf(&b, "%s: %s\n", kv.Key, strconv.Quote(kv.Value))
		case "tools", "extensions", "exclude_extensions", "memory", "isolation", "isolated", "max_turns", "persist_session", "session_dir", "inherit_context", "run_in_background", "enabled":
			fmt.Fprintf(&b, "%s: %s\n", kv.Key, kv.Value)
		case "modelRole":
			resolved, err := p.Resolve(string(schema.TargetPi), kv.Value)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", a.Path, err)
			}
			model, thinking := splitModelThinking(resolved)
			fmt.Fprintf(&b, "model: %s\n", model)
			if thinking != "" {
				fmt.Fprintf(&b, "thinking: %s\n", thinking)
			}
		case "systemPromptMode":
			fmt.Fprintf(&b, "prompt_mode: %s\n", kv.Value)
		case "inheritSkills":
			fmt.Fprintf(&b, "skills: %s\n", kv.Value)
		}
	}
	if !allowsNestedDelegation(a) {
		b.WriteString("disallowed_tools: Agent, get_subagent_result, steer_subagent\n")
	}
	b.WriteString("---\n")
	b.WriteString(a.Body)
	return b.Bytes(), nil
}

func allowsNestedDelegation(a *schema.Agent) bool {
	depth, err := strconv.Atoi(strings.TrimSpace(a.Lookup("maxSubagentDepth")))
	return err == nil && depth > 1
}

func splitModelThinking(value string) (model, thinking string) {
	colon := strings.LastIndex(value, ":")
	if colon < 0 {
		return value, ""
	}
	candidate := value[colon+1:]
	switch candidate {
	case "off", "minimal", "low", "medium", "high", "xhigh":
		return value[:colon], candidate
	default:
		return value, ""
	}
}
